### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/student-mapping-project/.streamlit/secrets.toml'

### ISSUE THREAD

**Issue by johnfelipe** [MiguelAHG/student-mapping-project#1]
```
2022-06-10 19:39:39.691 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/root/student-mapping-project/app_main.py", line 52, in <module>
    pw_hashed_bytes = st.secrets["password"].encode("utf8")
  File "/usr/local/lib/python3.8/dist-packages/streamlit/secrets.py", line 222, in __getitem__
    value = self._parse(True)[key]
  File "/usr/local/lib/python3.8/dist-packages/streamlit/secrets.py", line 141, in _parse
    with open(self._file_path, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/student-mapping-project/.streamlit/secrets.toml'

```

**Comment by MiguelAHG** [comment]
Hello, the error that you have shown is to be expected if you tried to run the web app locally. Streamlit uses the "secrets" system so that a web app can use private information without having it written in the app's script. I intentionally did not track changes in the `secrets.toml` file because it contains the link to a dataset with personal data. 

As mentioned in the README, instructions for local development of the Student Mapping Project will not be provided because the app uses sensitive data. The only reason that this repo is public is that I have deployed the app online using Streamlit Cloud. The repo is not intended to be used by other people.

**Comment by johnfelipe** [comment]
and can u share a example of that `secrets.tmol`

**Comment by MiguelAHG** [comment]
You can read this page from the Streamlit documentation to see an example: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management

**Comment by MiguelAHG** [comment]
I'm closing this issue for the reasons stated in my previous comment.
